language: perl6
perl6:
  - 2017.08
env:
  - PATH=$PATH:$HOME/.rakudobrew/bin PGDATABASE=test PGUSER=postgres
install:
  - rakudobrew build zef
  - zef install --depsonly .
before_script:
  - createdb test -U postgres
  - psql test -f schema.sql
addons:
  postgresql: "9.6"
