sudo: required
env:
  - PATH=$PATH:$HOME/.rakudobrew/bin PGDATABASE=test CACHED=$HOME/build_cache PGUSER=postgres PGVERSION=9.5
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
  - createdb testing123
install:
  - ./install.sh
before_script:
  - createdb test -U postgres
  - psql test -f schema.sql
script:
  - prove -Ilib -v -r --exec=perl6 t/
cache:
  directories:
    - $HOME/.rakudobrew
