sudo: required
env:
  - PATH=$PATH:$HOME/.rakudobrew/bin PGDATABASE=test CACHED=$HOME/build_cache PGUSER=postgres
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo ps aux|grep -i postg
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - sudo sed -i "s/port = ..../port = 5432/g" /etc/postgresql/9.5/main/postgresql.conf
  - sudo cp -v /etc/postgresql/9.{4,5}/main/pg_hba.conf && sudo service postgresql restart 9.5
  - psql -V
  - psql --list
  - psql -c 'select version()'
  - createdb testing123
install:
  - ./install.sh
before_script:
  - createdb test -U postgres
  - psql test -f schema.sql
script:
  - prove -Ilib -v -r --exec=perl6 t/
cache:
  directories:
    - $HOME/.rakudobrew
