sudo:
  false
env:
  - PATH=$PATH:$HOME/.rakudobrew/bin PGDATABASE=test CACHED=$HOME/build_cache
install:
  - ./install.sh
before_script:
  - createdb test -U postgres
  - psql test -c 'create table kv(k varchar not null primary key, v jsonb)'
script:
  - prove -Ilib -v -r --exec=perl6 t/
cache:
  directories:
    - $HOME/.rakudobrew
services:
  - postgresql
addons:
  postgresql: "9.4"

