env:
  - PATH=$PATH:$HOME/.rakudobrew/bin PGDATABASE=test CACHED=$HOME/build_cache
install:
  - ./install.sh
before_script:
  - createdb test -U postgres
script:
  - PERL6LIB=lib prove -v -r --exec=perl6 t/
cache:
  directories:
    - $HOME/.rakudobrew
services:
  - postgresql
addons:
  postgresql: "9.4"

