env:
  - PATH=$PATH:$HOME/.rakudobrew/bin
before_install:
  - git clone https://github.com/tadzik/rakudobrew.git $HOME/.rakudobrew
install:
  - ./install.sh
script:
  - PERL6LIB=lib prove -v -r --exec=perl6 t/
cache:
  directories:
    - $HOME/build_cache
